language: go

go:
  - 1.5

services:
    - mysql

install:
	- export CGO_CFLAGS=`mysql_config --cflags`
	- export CGO_LDFLAGS=`mysql_config --libs` 
    - go get github.com/mattn/goveralls
    - go get github.com/funny/utest
    - go get -d -v ./...
    - go build -v ./...

script:
    - go vet -x ./...
    - go test -v ./...
    - go test -covermode=count -coverprofile=profile.cov .

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci