language: go

sudo: required
dist: trusty

go:
    - 1.4.3
    - 1.5.2
    - tip

env:
    - CGO_CFLAGS="`mysql_config --cflags` -std=c99" CGO_LDFLAGS="`mysql_config --libs`" TEST_MYSQL_PASS=123

before_install:
    - sudo apt-get update
    - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password 123'
    - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password 123'
    - sudo apt-get -y install mysql-server
    - sudo /etc/init.d/mysql start

install:
    - go get github.com/mattn/goveralls
    - go get github.com/funny/utest
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/vet
    - go get -d -v ./...
    - go build -v ./...

script:
    - go vet -x ./...
    - go test -covermode=count -coverprofile=profile.cov .

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci